export const mockData = [
  {
    name: "Ronaldo",
    content: "cho anh chữ kí nhé",
    active: true,
    status: 1,
    time: "[2021, 0, 29]",
  },
  {
    name: "Messi",
    content: "cho anh chữ kí nhé",
    active: false,
    status: 2,
    time: "[2022, 0, 29]",
  },
  {
    name: "Công Phượng",
    content: "Dũng về đá bóng cho HAGL nhé",
    active: false,
    status: 2,
    time: "[2020, 0, 29]",
  },
  {
    name: "Ninh Dương Lan Ngọc",
    content: " a Trung, làm người yêu em được ko",
    active: false,
    status: 3,
    time: "[2007, 0, 29]",
  },
  {
    name: "Messi",
    content: "cho anh chữ kí nhé",
    active: false,
    status: 2,
    time: "[2022, 0, 29]",
  },
  {
    name: "Công Phượng",
    content: "Dũng về đá bóng cho HAGL nhé",
    active: false,
    status: 2,
    time: "[2020, 0, 29]",
  },
  {
    name: "Ninh Dương Lan Ngọc",
    content: " a Trung, làm người yêu em được ko",
    active: false,
    status: 3,
    time: "[2007, 0, 29]",
  },  {
    name: "Messi",
    content: "cho anh chữ kí nhé",
    active: false,
    status: 2,
    time: "[2022, 0, 29]",
  },
  {
    name: "Công Phượng",
    content: "Dũng về đá bóng cho HAGL nhé",
    active: false,
    status: 2,
    time: "[2020, 0, 29]",
  },
  {
    name: "Ninh Dương Lan Ngọc",
    content: " a Trung, làm người yêu em được ko",
    active: false,
    status: 3,
    time: "[2007, 0, 29]",
  },  {
    name: "Messi",
    content: "cho anh chữ kí nhé",
    active: false,
    status: 2,
    time: "[2022, 0, 29]",
  },
  {
    name: "Công Phượng",
    content: "Dũng về đá bóng cho HAGL nhé",
    active: false,
    status: 2,
    time: "[2020, 0, 29]",
  },
  {
    name: "Ninh Dương Lan Ngọc",
    content: " a Trung, làm người yêu em được ko",
    active: false,
    status: 3,
    time: "[2007, 0, 29]",
  },  {
    name: "Messi",
    content: "cho anh chữ kí nhé",
    active: false,
    status: 2,
    time: "[2022, 0, 29]",
  },
  {
    name: "Công Phượng",
    content: "Dũng về đá bóng cho HAGL nhé",
    active: false,
    status: 2,
    time: "[2020, 0, 29]",
  },
  {
    name: "Ninh Dương Lan Ngọc",
    content: " a Trung, làm người yêu em được ko",
    active: false,
    status: 3,
    time: "[2007, 0, 29]",
  },  {
    name: "Messi",
    content: "cho anh chữ kí nhé",
    active: false,
    status: 2,
    time: "[2022, 0, 29]",
  },
  {
    name: "Công Phượng",
    content: "Dũng về đá bóng cho HAGL nhé",
    active: false,
    status: 2,
    time: "[2020, 0, 29]",
  },
  {
    name: "Ninh Dương Lan Ngọc",
    content: " a Trung, làm người yêu em được ko",
    active: false,
    status: 3,
    time: "[2007, 0, 29]",
  },
];
